export * from './user.schema'

export * from './info.schema'
export * from './legal.schema'
export * from './feedback.schema'
export * from './contact.schema'
export * from './work.schema'
export * from './article.schema'
export * from './medical.schema'
export * from './topic.schema'
export * from './home.schema'